version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "02:00"
      timezone: "Europe/Stockholm"
    groups:
      actions-patch-minor:
        update-types: ["minor", "patch"]
