core:
  - changed-files:
    - any-glob-to-any-file: 'Sources/SSHCore/**'

app:
  - changed-files:
    - any-glob-to-any-file: 'App/**'

linux-gui:
  - changed-files:
    - any-glob-to-any-file: 'LinuxApp/**'

tests:
  - changed-files:
    - any-glob-to-any-file: 'Tests/**'

ci:
  - changed-files:
    - any-glob-to-any-file: '.github/**'

documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '**.md'

dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - 'Package.swift'
      - 'Package.resolved'
      - 'LinuxApp/Package.swift'
      - 'LinuxApp/Package.resolved'
